#python3 train.py -base_model att_cnn -maxlen 100
python3 train.py -base_model att_cnn -maxlen 200
python3 train.py -base_model att_cnn -maxlen 300
python3 train.py -base_model att_cnn -maxlen 400
python3 train.py -base_model att_cnn -maxlen 500
python3 train.py -base_model att_cnn -maxlen 600
python3 train.py -base_model att_cnn -maxlen 700
python3 train.py -base_model att_cnn -maxlen 800
python3 train.py -base_model att_cnn -maxlen 900
python3 train.py -base_model att_cnn -maxlen 1000
python3 train.py -base_model att_cnn -maxlen 1200
python3 train.py -base_model att_cnn -maxlen 1300
python3 train.py -base_model att_cnn -maxlen 1400
python3 train.py -base_model att_cnn -maxlen 1500
python3 train.py -base_model att_cnn -maxlen 1600
python3 train.py -base_model att_cnn -maxlen 1700
python3 train.py -base_model att_cnn -maxlen 1800
python3 train.py -base_model att_cnn -maxlen 1900
python3 train.py -base_model att_cnn -maxlen 2000
python3 train.py -base_model att_cnn -maxlen 2100